import { FaTiktok, FaWhatsapp } from "react-icons/fa"
import { FcGoogle } from "react-icons/fc"
import {
  LuBold,
  LuBookOpen,
  LuCalendar,
  LuCheck,
  LuChevronDown,
  LuChevronLeft,
  LuChevronRight,
  LuChevronsLeft,
  LuChevronsRight,
  LuChevronUp,
  LuCircle,
  LuCode,
  LuCopy,
  LuDownload,
  LuExternalLink,
  LuEye,
  LuEyeOff,
  LuFacebook,
  LuFileBarChart,
  LuFileImage,
  LuFolder,
  LuGamepad,
  LuGauge,
  LuGlobe2,
  LuHash,
  LuHeading1,
  LuHeading2,
  LuHeading3,
  LuHeading4,
  LuHeading5,
  LuHeading6,
  LuHelpCircle,
  LuHome,
  LuImage,
  LuImageOff,
  LuInfo,
  LuInstagram,
  LuItalic,
  LuLaptop2,
  LuLink,
  LuLinkedin,
  LuList,
  LuListOrdered,
  LuLoader2,
  LuLogIn,
  LuLogOut,
  LuMail,
  LuMenu,
  LuMessageCircle,
  LuMinus,
  LuMoon,
  LuMoreHorizontal,
  LuMoreVertical,
  LuPanelLeftClose,
  LuPanelRightClose,
  LuPencil,
  LuPlus,
  LuQuote,
  LuSave,
  LuSearch,
  LuSettings,
  LuShare,
  LuShare2,
  LuStrikethrough,
  LuSun,
  LuTable2,
  LuTag,
  LuTarget,
  LuText,
  LuTrash,
  LuTwitter,
  LuUnderline,
  LuUpload,
  LuUser,
  LuUsers,
  LuX,
  LuYoutube,
} from "react-icons/lu"
import { RiTwitterXLine } from "react-icons/ri"

import { IndonesiaFlag, USAFlag } from "./icon-flag"

export const Icon = {
  Account: LuUser,
  Add: LuPlus,
  Ads: LuTarget,
  Analytics: LuFileBarChart,
  ArrowBack: LuChevronLeft,
  ArrowForward: LuChevronRight,
  Article: LuText,
  BrokenImage: LuImageOff,
  Calendar: LuCalendar,
  Category: LuTag,
  Check: LuCheck,
  ChevronLeft: LuChevronLeft,
  ChevronsLeft: LuChevronsLeft,
  ChevronRight: LuChevronRight,
  ChevronsRight: LuChevronsRight,
  ChevronDown: LuChevronDown,
  ChevronUp: LuChevronUp,
  Circle: LuCircle,
  Close: LuX,
  Code: LuCode,
  Comment: LuMessageCircle,
  Copy: LuCopy,
  Dark: LuMoon,
  Dashboard: LuGauge,
  Download: LuDownload,
  Delete: LuTrash,
  Edit: LuPencil,
  Email: LuMail,
  ExternalLink: LuExternalLink,
  USAFlag: USAFlag,
  Facebook: LuFacebook,
  Folder: LuFolder,
  FormatBold: LuBold,
  FormatItalic: LuItalic,
  FormatListBulleted: LuList,
  FormatListNumbered: LuListOrdered,
  FormatQuote: LuQuote,
  FormatStrikethrough: LuStrikethrough,
  FormatUnderlined: LuUnderline,
  Gamepad: LuGamepad,
  GoogleColored: FcGoogle,
  Help: LuHelpCircle,
  H1: LuHeading1,
  H2: LuHeading2,
  H3: LuHeading3,
  H4: LuHeading4,
  H5: LuHeading5,
  H6: LuHeading6,
  Hash: LuHash,
  Home: LuHome,
  HorizontalRule: LuMinus,
  Image: LuImage,
  IndonesiaFlag: IndonesiaFlag,
  Info: LuInfo,
  Instagram: LuInstagram,
  Language: LuGlobe2,
  Laptop: LuLaptop2,
  Light: LuSun,
  Link: LuLink,
  Linkedin: LuLinkedin,
  Login: LuLogIn,
  Logout: LuLogOut,
  Media: LuFileImage,
  Menu: LuMenu,
  MoreHorizontal: LuMoreHorizontal,
  MoreVertical: LuMoreVertical,
  Moon: LuMoon,
  PanelLefttClose: LuPanelLeftClose,
  PanelRightClose: LuPanelRightClose,
  Person: LuUser,
  Read: LuBookOpen,
  Report: LuInfo,
  Save: LuSave,
  Setting: LuSettings,
  Search: LuSearch,
  Share: LuShare,
  Share2: LuShare2,
  SignIn: LuLogIn,
  SignOut: LuLogOut,
  Spinner: LuLoader2,
  Sun: LuSun,
  Table: LuTable2,
  Text: LuText,
  Tiktok: FaTiktok,
  Topic: LuTag,
  Trash: LuTrash,
  Twitter: LuTwitter,
  Upload: LuUpload,
  User: LuUser,
  Users: LuUsers,
  ViewSidebar: LuPanelRightClose,
  View: LuEye,
  Visibility: LuEye,
  VisibilityOff: LuEyeOff,
  WhatsApp: FaWhatsapp,
  X: RiTwitterXLine,
  Youtube: LuYoutube,
}
